modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="shaftly"
version="1.0.0"
displayName="shaftly"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="pickle, MCreator"

[[dependencies.shaftly]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




